rolling_windows:
  short_window_days: 7
  long_window_days: 14
safety_rules:
  max_daily_increase_pct: 0.19174797407324215
  max_daily_decrease_pct: 0.10105994578295761
  freeze_roas_threshold: 0.5
  freeze_health_threshold: 0.2
  min_budget: 1.0
  max_budget_pct_of_total: 0.4
  cold_start_days: 3
  cold_start_max_increase_pct: 0.1
  # NEW: New adset budget initialization
  new_adset_initial_fraction: 0.5
  new_adset_max_initial_budget: 100.0
decision_rules:
  very_low_roas_threshold: 1.0
  low_roas_threshold: 2.1948144802903498
  medium_roas_threshold: 2.1834347898661637
  medium_high_roas_threshold: 2.5
  high_roas_threshold: 3.669536500409154
  very_high_roas_threshold: 3.5
  excellent_roas_threshold: 3.5
  high_vs_adset_threshold: 1.2
  high_vs_campaign_threshold: 1.15
  high_vs_account_threshold: 1.1
  low_vs_adset_threshold: 0.8
  strong_rising_trend: 0.1000562916708533
  strong_falling_trend: -0.17856997731170887
  moderate_rising_trend: 0.05
  moderate_falling_trend: -0.05
  high_efficiency_threshold: 0.14763327094232798
  low_efficiency_threshold: 0.012256463161084011
  high_revenue_per_impression: 0.08
  low_revenue_per_impression: 0.02
  high_revenue_per_click: 2.5
  low_revenue_per_click: 1.0
  healthy_threshold: 0.7165996316800475
  unhealthy_threshold: 0.3877105418031501
  excellent_health_threshold: 0.85
  cold_start_days: 3
  learning_phase_days_early: 7
  learning_phase_days_mid: 14
  learning_phase_days_late: 21
  learning_phase_days: 20
  established_days: 21
  high_spend_threshold: 100
  low_spend_threshold: 10
  spend_trend_rising: 0.15
  spend_trend_falling: -0.2
  high_clicks_threshold: 50
  high_impressions_threshold: 5000
  high_reach_threshold: 1000
  weekend_boost_factor: 1.02
  weekday_factor: 1.0
  q4_boost_factor: 1.03
  aggressive_increase_pct: 0.2193700315892974
  moderate_increase_pct: 0.09458327528535912
  conservative_increase_pct: 0.05
  moderate_decrease_pct: 0.1188873337948801
  aggressive_decrease_pct: 0.17499372895450072
  maintenance_pct: 0.0
  gradient_enabled: true
  gradient_smoothing_factor: 0.34699260385108666
  gradient_range_size_factor: 0.5
  gradient_start_factor: 0.5
  gradient_end_factor: 1.0
  trend_scaling_enabled: true
  trend_strong_threshold: 0.2
  trend_moderate_threshold: 0.1
  trend_weak_threshold: 0.05
  trend_strong_factor: 1.0
  trend_moderate_start_factor: 0.7
  trend_moderate_range_factor: 0.3
  trend_weak_start_factor: 0.4
  trend_weak_range_factor: 0.3
  trend_min_factor: 0.3
  health_score_multiplier_enabled: true
  relative_performance_max_scale: 1.5
  relative_performance_multiplier: 2.0
  budget_relative_scaling_enabled: true
  health_score_min_multiplier: 0.5
  health_score_max_multiplier: 1.0
  relative_performance_boost_base: 0.05
  relative_performance_boost_campaign: 0.03
  relative_performance_boost_medium: 0.3
  click_efficiency_threshold: 1.2
  default_health_score: 0.5
  default_efficiency: 0.05
  large_budget_threshold: 100
  medium_budget_threshold: 20
  small_budget_max_increase: 0.2
  medium_budget_max_increase: 0.15
  large_budget_max_increase: 0.1
  low_clicks_threshold: 20
  medium_clicks_threshold: 100
  low_clicks_multiplier: 0.8
  medium_clicks_multiplier: 0.9
  q4_week_48_boost: 0.01
  q4_week_49_boost: 0.02
  q4_week_50_51_boost: 0.03
  q4_week_52_boost: 0.02
  min_diversity_threshold: 5
  min_active_ads_threshold: 3
  diversity_bonus_pct: 0.1
  max_spend_concentration: 0.8
  spend_concentration_penalty_pct: 0.2
  max_roas_std: 0.5
  consistency_bonus_pct: 0.1
  min_format_diversity: 3
  format_diversity_bonus_pct: 0.05
  outlier_multiplier_threshold: 3.0
  outlier_penalty_pct: 0.15
advanced_concepts:
  adaptive_target_enabled: true
  marginal_roas_enabled: true
  budget_utilization_enabled: true
  low_utilization_threshold: 0.7
  high_utilization_threshold: 0.95
  low_utilization_adjustment_factor: 0.5
  high_utilization_boost_factor: 1.1
  adaptive_target_adjustment_factor: 0.3
  marginal_roas_base_factor: 0.95
  marginal_roas_range_factor: 0.05
  smoothing_enabled: true
  smoothing_alpha: 0.7
  momentum_enabled: true
  momentum_days: 3
monthly_budget:
  monthly_budget_cap: 10000.0
  conservative_factor: 0.95
  reset_day: 1
  archive_daily_allocations: true
  # NEW: Period management for mid-month starts
  period_length_days: 30
  # NEW: Conservative start on first day
  day1_budget_multiplier: 0.8
